### ISSUE TITLE
Errors on fresh install

### ISSUE THREAD

**Issue by Manvel** [Manvel/Privacy-Manager#8]
# 2 Errors are being thrown on fresh install:
## Error 1:
`Unchecked runtime.lastError while running webRequestInternal.addEventListener: You need to request host permissions in the manifest file in order to be notified about requests from the webRequest API.
    at chrome-extension://ejajldemclbeoamcblddhmfeepfeamjk/js/back.js:124:41
    at chrome-extension://ejajldemclbeoamcblddhmfeepfeamjk/js/back.js:146:3
`
## Error 2:
`Error in response to storage.get: TypeError: Cannot read property 'collectHeaders' of undefined
    at Object.callback (chrome-extension://ejajldemclbeoamcblddhmfeepfeamjk/js/back.js:37:25)
    at chrome-extension://ejajldemclbeoamcblddhmfeepfeamjk/js/back.js:35:3
    at chrome-extension://ejajldemclbeoamcblddhmfeepfeamjk/js/back.js:146:3`

**Note:** Release for v3 is blocked

**Comment by Manvel** [comment]
This is fixed [here](https://github.com/Manvel/Privacy-Manager/commit/89988c9d687ef141d36fa92d82a0ddeff7f0e663).
